version: 2.1
jobs:
  test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: |
            npm ci

  publish:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Setup Environment Variables
          command: |
            REGISTRY=vcalendars/scraper-worker
            echo $REGISTRY
            echo "export REGISTRY=$REGISTRY" >> $BASH_ENV
            TAG=$CIRCLE_TAG
            echo $TAG
            echo "export TAG=$TAG" >> $BASH_ENV
      - run:
          name: Run Docker Build
          command: |
            docker build -t $REGISTRY:$TAG .
      - run:
          name: Push Docker Image
          command: |
            echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME $DOCKER_REGISTRY_URL --password-stdin
            docker push $REGISTRY:$TAG

  publish-latest:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Setup Environment Variables
          command: |
            REGISTRY=vcalendars/scraper-worker
            echo $REGISTRY
            echo "export REGISTRY=$REGISTRY" >> $BASH_ENV
            TAG=$CIRCLE_TAG
            echo $TAG
            echo "export TAG=$TAG" >> $BASH_ENV
      - run:
          name: Run Docker Build
          command: |
            docker build -t $REGISTRY:$TAG .
            docker tag $REGISTRY:$TAG $REGISTRY:latest
      - run:
          name: Push Docker Image
          command: |
            echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME $DOCKER_REGISTRY_URL --password-stdin
            docker push $REGISTRY:$TAG
            docker push $REGISTRY:latest

workflows:
  version: 2
  ci:
    jobs:
      - test:
          filters:
            tags:
              only: /.*/

      - publish:
          requires:
            - test
          filters:
            tags:
              only: /v([0-9])*.([0-9])*.([0-9])*-.*/
            branches:
              ignore: /.*/

      - publish-latest:
          requires:
            - test
          filters:
            tags:
              only: /v([0-9])*.([0-9])*.([0-9])*/
            branches:
              ignore: /.*/
